#pragma once

#define MODE_0_ACCU_MAX_ALLOWED_POWER 40000 // W -> 40 kW
#define MODE_0_ACCU_MAX_ALLOWED_CURRENT 120 // A
#define MODE_0_MOTOR_MAX_ALLOWED_TORQUE 120 // Nm

#define MODE_1_ACCU_MAX_ALLOWED_POWER 60000 // W -> 60 kW
#define MODE_1_ACCU_MAX_ALLOWED_CURRENT 200 // A
#define MODE_1_MOTOR_MAX_ALLOWED_TORQUE 150 // Nm

#define MODE_2_ACCU_MAX_ALLOWED_POWER 80000 // W -> 80 kW
#define MODE_2_ACCU_MAX_ALLOWED_CURRENT 250 // A
#define MODE_2_MOTOR_MAX_ALLOWED_TORQUE 150 // Nm

#define MODE_3_ACCU_MAX_ALLOWED_POWER 60000 // W -> 60 kW
#define MODE_3_ACCU_MAX_ALLOWED_CURRENT 200 // A
#define MODE_3_MOTOR_MAX_ALLOWED_TORQUE 150 // Nm

#define MODE_4_ACCU_MAX_ALLOWED_POWER 80000 // W -> 80 kW
#define MODE_4_ACCU_MAX_ALLOWED_CURRENT 250 // A
#define MODE_4_MOTOR_MAX_ALLOWED_TORQUE 150 // Nm
