#ifndef PINS_DASHBOARD_H
#define PINS_DASHBOARD_H

#define DASHBOARD_PIN_BUTTON_RESET D7
#define DASHBOARD_PIN_BUTTON_START D9
#define DASHBOARD_PIN_LED_RED      D6 // PWM
#define DASHBOARD_PIN_LED_YELLOW   D5 // PWM
#define DASHBOARD_PIN_LED_GREEN    D3 // PWM

#endif // PINS_DASHBOARD_H