#ifndef PINS_DASHBOARD_H
#define PINS_DASHBOARD_H

#define DASHBOARD_PIN_BUTTON_RESET PA_13
#define DASHBOARD_PIN_BUTTON_START PA_14
#define DASHBOARD_PIN_LED_RED      PA_1  // PWM
#define DASHBOARD_PIN_LED_YELLOW   PA_0  // PWM
#define DASHBOARD_PIN_LED_GREEN    PA_15 // PWM

#endif // PINS_DASHBOARD_H