#ifndef PINS_PEDAL_H
#define PINS_PEDAL_H

#define PEDAL_PIN_STEERING_ANGLE_SENSOR   PB_1
#define PEDAL_PIN_SPRING_TRAVEL_SENSOR_FL PA_3
#define PEDAL_PIN_SPRING_TRAVEL_SENSOR_FR PC_4
#define PEDAL_PIN_ROTATION_ANGLE_GAS_1    PC_1
#define PEDAL_PIN_ROTATION_ANGLE_GAS_2    PA_0
#define PEDAL_PIN_ROTATION_ANGLE_BRAKE    PB_0
#define PEDAL_PIN_RPM_SENSOR_FL           PB_2
#define PEDAL_PIN_RPM_SENSOR_FR           PB_4

#endif // PINS_PEDAL_H