#ifndef PINS_DASHBOARD_H
#define PINS_DASHBOARD_H

#define DASHBOARD_PIN_BUTTON_LOWER D7
#define DASHBOARD_PIN_BUTTON_UPPER D9
#define DASHBOARD_PIN_LED_1        D6 // PWM
#define DASHBOARD_PIN_LED_2        D5 // PWM
#define DASHBOARD_PIN_LED_3        D3 // PWM

#endif // PINS_DASHBOARD_H