#ifndef PINS_DASHBOARD_H
#define PINS_DASHBOARD_H

#define DASHBOARD_PIN_BUTTON_RESET PB_10
#define DASHBOARD_PIN_BUTTON_START PC_7
#define DASHBOARD_PIN_LED_RED      PB_4  // PWM
#define DASHBOARD_PIN_LED_YELLOW   PB_5  // PWM
#define DASHBOARD_PIN_LED_GREEN    PA_10 // PWM

#endif // PINS_DASHBOARD_H