#ifndef PINS_PEDAL_H
#define PINS_PEDAL_H

#define PEDAL_PIN_STEERING_ANGLE_SENSOR   A0
#define PEDAL_PIN_SPRING_TRAVEL_SENSOR_FL A1
#define PEDAL_PIN_SPRING_TRAVEL_SENSOR_FR A2
#define PEDAL_PIN_ROTATION_ANGLE_GAS_1    A3
#define PEDAL_PIN_ROTATION_ANGLE_GAS_2    A4
#define PEDAL_PIN_ROTATION_ANGLE_BRAKE    A5

#endif // PINS_PEDAL_H