#ifndef PINS_PEDAL_H
#define PINS_PEDAL_H

#define PEDAL_PIN_STEERING_ANGLE_SENSOR   PA_0
#define PEDAL_PIN_SPRING_TRAVEL_SENSOR_FL PA_4
#define PEDAL_PIN_SPRING_TRAVEL_SENSOR_FR PA_1
#define PEDAL_PIN_ROTATION_ANGLE_GAS_1    PB_0
#define PEDAL_PIN_ROTATION_ANGLE_GAS_2    PC_1
#define PEDAL_PIN_ROTATION_ANGLE_BRAKE    PC_0
#define PEDAL_PIN_RPM_SENSOR_FL           PA_13
#define PEDAL_PIN_RPM_SENSOR_FR           PA_14

#define PEDAL_CAN PB_8,PB_9

#define PEDAL_PIN_ALIVE LED2

#endif // PINS_PEDAL_H