#ifndef PINS_PEDAL_H
#define PINS_PEDAL_H

#define PEDAL_PIN_STEERING_ANGLE_SENSOR   A5
#define PEDAL_PIN_SPRING_TRAVEL_SENSOR_FL A4
#define PEDAL_PIN_SPRING_TRAVEL_SENSOR_FR A3
#define PEDAL_PIN_ROTATION_ANGLE_GAS_1    A0
#define PEDAL_PIN_ROTATION_ANGLE_GAS_2    A1
#define PEDAL_PIN_ROTATION_ANGLE_BRAKE    A2
#define PEDAL_PIN_RPM_SENSOR_FL           D12
#define PEDAL_PIN_RPM_SENSOR_FR           D11

#define PEDAL_CAN D10,D2

#endif // PINS_PEDAL_H