#ifndef SD_LOG_IDS_H
#define SD_LOG_IDS_H

// Refresh rates in Hz

#define SD_LOG_REFRESH_RATE_PEDAL_POSITION 60

#define SD_LOG_REFRESH_RATE_MOTOR_CONTROLLER_SPEED 120
#define SD_LOG_REFRESH_RATE_MOTOR_CONTROLLER_CURRENT 120
#define SD_LOG_REFRESH_RATE_MOTOR_CONTROLLER_MOTOR_TEMP 1
#define SD_LOG_REFRESH_RATE_MOTOR_CONTROLLER_SERVO_TEMP 1
#define SD_LOG_REFRESH_RATE_MOTOR_CONTROLLER_AIR_TEMP 1

#define SD_LOG_REFRESH_RATE_RPM 120

#define SD_LOG_REFRESH_RATE_COOLING_PUMP_SPEED 1

#endif // SD_LOG_IDS_H