#ifndef PINS_DASHBOARD_H
#define PINS_DASHBOARD_H

// Same as old one, only new pins

#define DASHBOARD_PIN_BUTTON_RESET D12
#define DASHBOARD_PIN_BUTTON_START D11
#define DASHBOARD_PIN_CAL D0
#define DASHBOARD_PIN_LED_RED D9
#define DASHBOARD_PIN_LED_GREEN A6
#define DASHBOARD_PIN_LED_BLUE A2
#define DASHBOARD_PIN_LED_CAL D3
#define DASHBOARD_PIN_LED_RTD D1
#define DASHBOARD_PIN_LED_LCT D6
// #define DASHBOARD_PIN_LED_IMD
// #define DASHBOARD_PIN_LED_BMS

#define DASHBOARD_CAN D10, D2

#endif // PINS_DASHBOARD_H