// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: CarUi

#ifndef _CARUI_UI_H
#define _CARUI_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
    // SCREEN: ui_Screen1
    void ui_Screen1_screen_init(void);
    void ui_event_Screen1(lv_event_t *e);
    extern lv_obj_t *ui_Screen1;
    extern lv_obj_t *ui_logoImage;
    // SCREEN: ui_Screen2
    void ui_Screen2_screen_init(void);
    extern lv_obj_t *ui_Screen2;
    extern lv_obj_t *ui_Label1;
    extern lv_obj_t *ui_Bar1;
    extern lv_obj_t *ui_Label2;
    extern lv_obj_t *ui_Bar2;
    extern lv_obj_t *ui_Label3;
    extern lv_obj_t *ui_Bar3;
    extern lv_obj_t *ui_Label4;
    extern lv_obj_t *ui_Bar4;
    extern lv_obj_t *ui_Arc1;
    extern lv_obj_t *ui_Arc2;
    extern lv_obj_t *ui_Label6;
    extern lv_obj_t *ui_Label5;
    extern lv_obj_t *ui_Panel2;
    extern lv_obj_t *ui_Label8;
    extern lv_obj_t *ui_Panel1;
    extern lv_obj_t *ui_Label7;
    extern lv_obj_t *ui_Bar6;
    extern lv_obj_t *ui_Bar5;
    extern lv_obj_t *ui____initial_actions0;

    LV_IMG_DECLARE(ui_img_logo_png); // assets\logo.png

    void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
