#ifndef PINS_DASHBOARD_H
#define PINS_DASHBOARD_H

// Same as old one, only new pins

#define DASHBOARD_PIN_BUTTON_RESET D12
#define DASHBOARD_PIN_BUTTON_START D11
#define DASHBOARD_PIN_CAL          D0
#define DASHBOARD_PIN_LED_RED      D9
#define DASHBOARD_PIN_LED_YELLOW   D3
#define DASHBOARD_PIN_LED_GREEN    D1

#define DASHBOARD_CAN D10,D2

#endif // PINS_DASHBOARD_H